"""Changes for admin

Revision ID: c83554cea7fa
Revises: 6bd7dbd0cfc1
Create Date: 2025-03-07 22:04:47.093068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83554cea7fa'
down_revision: Union[str, None] = '6bd7dbd0cfc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
